### ISSUE TITLE
shader for desaturate dark colors 

### ISSUE THREAD

**Issue by geextahslex** [butterw/bShaders#3]
Hi,
I'm looking for a shader that desaturates only the dark colors (0-40 rgb value) by amount x (so it's customizable)
Could you help me out with that?

Thank you

**Comment by butterw** [comment]
You just need to write a shader that applies a desaturation curve.

```
//!HOOK MAIN
//!BIND HOOKED
//!DESC Dark Desaturation

#define Strength 0.5
#define Thresh 40/255.
#define CoefLuma vec4(0.2126, 0.7152, 0.0722, 0) //sRGB, HDTV

/* simple threshold with mpv glsl 
Strength*desaturation [0 to1.0], 0: full color, 1: grayscale.
*/

vec4 hook()  {
   vec4 c0 = HOOKED_texOff(0);
   vec3 desaturation = 1- step(Thresh, c0.rgb);
   // return vec4(desaturation, 1);
   c0.rgb = mix(c0.rgb, vec3(dot(c0, CoefLuma)), Strength*desaturation);

   return c0;
}
```

**Comment by geextahslex** [comment]
Thanks for your reply.

I saved this as a .glsl shader and put it inside my mpv config file. But somehow there is no effect.

**Comment by butterw** [comment]
You need a HOOK to run it in mpv. I've added the corresponding block to the code.
Adjust as required, a curve will be better as it can avoid the threshold effect.

**Comment by geextahslex** [comment]
Yapp that worked like a charm.
Thank you :) God bless you

**Comment by butterw** [comment]
you can get a smoother transition by using smoothstep instead of step:

#define w 5/255.
vec3 desaturation = smoothstep(Thresh + w, Thresh - w, c0.rgb);

**Comment by geextahslex** [comment]
I will try it out, but its already hammering my CPU ^^

**Comment by geextahslex** [comment]
When using smoothstep, what does the variable "w" stand for? 

Oh okay I think I get it, so when the threshold is 30, he adds and substracts 5 (w) so 25-35 is the smooth transition area?

**Comment by geextahslex** [comment]
I'm trying to use this shader to desaturate dark colors, do you know why it produces this magenta/purple effect?
look at the steering wheel
off (normal)
![dfgfgdfg](https://github.com/natural-harmonia-gropius/hdr-toys/assets/139760266/a59add9d-73c0-4d00-9317-cc10887eb321)
on (broken magenta/purple)
![magenta elite](https://github.com/natural-harmonia-gropius/hdr-toys/assets/139760266/778deba3-5344-4535-9089-e09809612953)
what it should actually look like
![elite pgoto](https://github.com/natural-harmonia-gropius/hdr-toys/assets/139760266/6b71475a-c245-4d7b-b8da-89d1a910ca31)
